### ISSUE TITLE
Add option to disable keybinding

### ISSUE THREAD

**Issue by fuine** [javier-lopez/sprunge.vim#16]
I use several `<Leader>s(some letter here)` and default mapping for this plugin overrides them all. While I can set some combination that I don't currently use in `g:sprunge_map` I would like to disable the keybinding completely.

**Comment by chilicuil** [comment]
Hello,

You can do so by adding an internal mapping, eg:

```
nmap <Plug>DisableSprungeMapping <Plug>Sprunge
xmap <Plug>DisableSprungeMapping <Plug>Sprunge
```

It would be a good idea to add it to the documentation, though.
